#!/bin/dash
# Append the current url to Periodical's url list.
# Copyright 2012 Tom Vincent <http://tlvince.com/contact/>
# dwb: ep

local="${XDG_DATA_HOME:-$HOME/.local/share}/periodical"
urls="$local/urls"

mkdir -p "$local"
echo "$DWB_URI" >> "$urls"
sort --unique --output="$urls" "$urls"
